spring:

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: rootroot
    url: jdbc:mysql://localhost:3306/postzy?createDatabaseIfNotExist=true

  jpa:
    hibernate: ddl-auto=create-drop

  flyway:
    locations: classpath:db/migration