CREATE TABLE post (
 id VARBINARY(36) NOT NULL PRIMARY KEY,
 parentId VARBINARY(36) NULL DEFAULT NULL,
 title VARCHAR(100) NOT NULL,
 slug VARCHAR(120) NOT NULL,
 created_at DATETIME NOT NULL,
 updated_at DATETIME,
 published_at DATETIME,
 content TEXT NOT NULL
);

CREATE TABLE category (
 id VARBINARY(36) NOT NULL PRIMARY KEY,
 parentId VARBINARY(36) NULL DEFAULT NULL,
 title VARCHAR(75) NOT NULL,
 slug VARCHAR(120) NOT NULL,
 content TEXT NULL DEFAULT NULL,
 created_at DATETIME NOT NULL,
 updated_at DATETIME,
 published_at DATETIME
);

CREATE TABLE post_category (
 id VARBINARY(36) NOT NULL PRIMARY KEY,
 post_id VARBINARY(36) NOT NULL,
 category_id VARBINARY(36) NOT NULL,
 CONSTRAINT `fk_post` FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
 CONSTRAINT `fk_category` FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE NO ACTION ON UPDATE NO ACTION
);